tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false

[git_hooks.commit-msg]
script = "cog verify --file $1"

[commit_types]
